using ComfyTyped.Core;
using ComfyTyped.Generated;
using ComfyTyped.SwarmUI;
using ComfyTyped.Types;
using Newtonsoft.Json.Linq;
using SwarmUI.Builtin_ComfyUIBackend;
using VideoStages.Execution.Audio;
using VideoStages.Execution.Graph;
using VideoStages.Generated;

namespace VideoStages.Architectures.Ltx2;

internal sealed class LtxAudioInjector(
    WorkflowGenerator g,
    RootVideoStageResizer rootVideoStageResizer)
{
    private const int AudioInjectionEnsureFallbackSlot = 50;

    /// <summary>
    /// Injects <paramref name="audio"/> as the sampling audio latent. With no
    /// <paramref name="preserveWindows"/>, the whole track is preserved (solid 0.0 mask). With
    /// windows, only those seconds-ranges are preserved and the gaps are regenerated by the model
    /// — the audio-span conditioning path (spans over no locked base track).
    /// </summary>
    public bool TryInject(
        WGNodeData audio,
        bool matchVideoLengthToAudio = true,
        IReadOnlyList<(double Start, double End)> preserveWindows = null)
    {
        if (audio is null || !g.IsLTXV2() || g.CurrentAudioVae is null)
        {
            return false;
        }

        WorkflowBridge bridge = WorkflowBridge.Create(g.Workflow);
        (List<string> concatIds, HashSet<string> removableSourceIds) = FindConcatsToReplace(bridge);
        if (concatIds.Count == 0)
        {
            return false;
        }

        WGNodeData adjustedAudio = audio;
        if (matchVideoLengthToAudio)
        {
            JToken lengthFramesAudioSource = LtxAudioPathResolution.ResolveLengthToFramesAudioSource(
                bridge,
                audio.Path,
                StableNodeIds.Id(g, StableNodeIds.AudioInjection, AudioInjectionEnsureFallbackSlot));
            SwarmAudioLengthToFramesNode lengthToFrames = CreateLengthToFramesNode(
                bridge,
                lengthFramesAudioSource,
                ResolveFramesPerSecond());
            ApplyFramesConnectionToRemovableAudioSources(bridge, removableSourceIds, lengthToFrames.Frames);
            BridgeSync.SyncLastId(g);
            LtxFrameCountConnector.ApplyToExistingSources(g, WorkflowBridge.ToPath(lengthToFrames.Frames));
            adjustedAudio = new(
                WorkflowBridge.ToPath(lengthToFrames.Audio),
                g,
                WGNodeData.DT_AUDIO,
                g.CurrentAudioVae.Compat);
        }

        WGNodeData encodedAudio = adjustedAudio.EncodeToLatent(g.CurrentAudioVae);
        bridge = WorkflowBridge.Create(g.Workflow);
        NodeOutput<LatentType> maskedLatent = preserveWindows is { Count: > 0 }
            ? AudioPreserveWindowBuilder.AddMask(
                g,
                bridge,
                encodedAudio.Path,
                preserveWindows,
                stableIdSlot: 0).Latent
            : CreateAudioMaskNode(bridge, encodedAudio.Path).LATENT;
        ReplaceAudioLatentConnections(bridge, concatIds, maskedLatent);
        RemoveUnusedSourceNodes(bridge, removableSourceIds);
        return true;
    }

    /// <summary>
    /// Encodes <paramref name="audio"/> and applies the preserve-windows noise mask WITHOUT touching any
    /// concat — for clips whose AV latent is built later from <c>AttachedAudio</c>: core
    /// <c>AsSamplingLatent</c> concats a pre-encoded audio latent as-is, keeping this mask, whereas raw
    /// attached audio would be baked fully-preserved (locking silent-bed gaps). Returns null when the
    /// graph state can't support it (not LTXV2 / no audio VAE / no windows).
    /// </summary>
    public WGNodeData TryBuildPreserveWindowedAudioLatent(
        WGNodeData audio,
        IReadOnlyList<(double Start, double End)> preserveWindows,
        int stableIdSlot)
    {
        if (audio is null
            || preserveWindows is not { Count: > 0 }
            || !g.IsLTXV2()
            || g.CurrentAudioVae is null)
        {
            return null;
        }
        return AudioPreserveWindowBuilder.TryBuild(
            g,
            audio,
            preserveWindows,
            stableIdSlot);
    }

    private static (List<string> ConcatIds, HashSet<string> RemovableSourceIds)
        FindConcatsToReplace(WorkflowBridge bridge)
    {
        List<string> concatIds = [];
        HashSet<string> removableSourceIds = [];
        foreach (LTXVConcatAVLatentNode concat in bridge.Graph.NodesOfType<LTXVConcatAVLatentNode>())
        {
            if (concat.AudioLatent.Connection?.Node is not LTXVEmptyLatentAudioNode emptyAudio)
            {
                continue;
            }
            concatIds.Add(concat.Id);
            removableSourceIds.Add(emptyAudio.Id);
        }
        return (concatIds, removableSourceIds);
    }

    private SwarmAudioLengthToFramesNode CreateLengthToFramesNode(WorkflowBridge bridge, JToken audioPath, int fps)
    {
        SwarmAudioLengthToFramesNode node = new SwarmAudioLengthToFramesNode().With(
            FrameRate: fps);
        node.AudioInput.TryConnectFromPath(bridge, audioPath as JArray);
        bridge.AddNode(node, StableNodeIds.Id(g, StableNodeIds.AudioInjection, 100));
        return node;
    }

    private int ResolveFramesPerSecond()
    {
        int fps = g.GetVideoExecutionPlanContext()?.Plan.FramesPerSecond
            ?? g.UserInput.Get(
                SwarmUI.Text2Image.T2IParamTypes.VideoFPS,
                LtxStageRuntimeSettings.DefaultFps);
        return fps > 0 ? fps : LtxStageRuntimeSettings.DefaultFps;
    }

    private static void ApplyFramesConnectionToRemovableAudioSources(
        WorkflowBridge bridge,
        HashSet<string> sourceIds,
        NodeOutput<IntType> framesOutput)
    {
        foreach (string sourceId in sourceIds)
        {
            LTXVEmptyLatentAudioNode emptyAudio = bridge.Graph.GetNode<LTXVEmptyLatentAudioNode>(sourceId);
            if (emptyAudio is null)
            {
                continue;
            }
            emptyAudio.FramesNumber.ConnectTo(framesOutput);
        }
    }

    private SetLatentNoiseMaskNode CreateAudioMaskNode(WorkflowBridge bridge, JArray encodedAudioPath)
    {
        int width = g.UserInput.GetImageWidth();
        int height = g.UserInput.GetImageHeight();
        if (rootVideoStageResizer.TryGetRootStageResolution(out int rootWidth, out int rootHeight))
        {
            width = rootWidth;
            height = rootHeight;
        }

        SolidMaskNode solidMask = new SolidMaskNode().With(
            Value: 0.0,
            Width: width,
            Height: height);
        bridge.AddNode(solidMask, StableNodeIds.Id(g, StableNodeIds.AudioInjection, 200));

        SetLatentNoiseMaskNode setMask = new SetLatentNoiseMaskNode().With(
            Mask: solidMask.MASK);
        setMask.Samples.TryConnectFromPath(bridge, encodedAudioPath);
        bridge.AddNode(setMask, StableNodeIds.Id(g, StableNodeIds.AudioInjection, 300));
        return setMask;
    }

    private static void ReplaceAudioLatentConnections(
        WorkflowBridge bridge,
        List<string> concatIds,
        NodeOutput<LatentType> maskedLatent)
    {
        foreach (string concatId in concatIds)
        {
            LTXVConcatAVLatentNode concat = bridge.Graph.GetNode<LTXVConcatAVLatentNode>(concatId);
            if (concat is null)
            {
                continue;
            }
            concat.AudioLatent.ConnectTo(maskedLatent);
        }
    }

    private void RemoveUnusedSourceNodes(WorkflowBridge bridge, HashSet<string> removableSourceIds)
    {
        g.UsedInputs = null;
        foreach (string sourceId in removableSourceIds)
        {
            if (!g.NodeIsConnectedAnywhere(sourceId))
            {
                VideoGraphHelpers.RemoveNode(g, bridge, sourceId);
            }
        }
    }

}
